// Life is Strange: Double Exposure - Ultrawide Fix (Windows front-end)
//
// Copyright (C) 2026 Kiri11.  Free software under the GNU General Public
// License, version 3 or later - see LICENSE for the full terms.
//
// Additional term under GPL-3 section 7(b): every copy or modified version,
// in source or binary form, must preserve this notice and credit the
// original author, Kiri11, with a link to the original project at
// https://github.com/kiri11/Life-is-Strange-Double-Exposure-Ultrawide.
//
// This is deliberately a THIN front-end. It contains no patch logic of its own:
// every option below runs patcher.py, which is the single source of truth for
// what gets written to the executable, the game data files and Engine.ini.
// An earlier version of this file reimplemented the byte patches in C# and
// silently drifted out of sync with the Python one, which is exactly the bug
// this structure prevents.
//
// It prefers `uv run`, which needs no virtualenv and fetches the one optional
// dependency (blake3, used by the game-files step) automatically. Failing that
// it uses the Python launcher, then plain python, and on a machine with no
// Python at all it downloads python.org's embeddable build into tools/python
// and runs the patcher with that - so the fix works either way. Each of those
// is tried in turn rather than picked once: uv without a network, or the
// zero-byte Microsoft Store python.exe, must not be the end of the road on a
// machine that has another way to run the script.
//
// Build (stock .NET Framework compiler, no SDK required):
//   %WINDIR%\Microsoft.NET\Framework64\v4.0.30319\csc.exe /target:winexe ^
//     /win32icon:LiSUltrawidePatcher.ico ^
//     /out:LiSUltrawidePatcher.exe LiSUltrawidePatcher.cs ^
//     /r:System.dll /r:System.Windows.Forms.dll /r:System.Drawing.dll ^
//     /r:System.IO.Compression.dll /r:System.IO.Compression.FileSystem.dll
//
// That is the same line .github/workflows/build.yml runs, and the exe users get
// is the one it produces - the binary is not in the repository, so it cannot
// drift from this file. The icon is generated by tools/make_icon.py.

using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.IO.Compression;
using System.Net;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows.Forms;

// Identity for the file itself - Explorer's Details tab, the digital-signature
// dialog if this is ever signed, and any bug report that quotes a file version.
// Nothing here is shown in the window: the version a user needs to quote is the
// one patcher.py prints into the log, and these must agree.
//
// The version is the release date plus that day's build number - the same string
// as the release tag (v2026.08.31.1). AssemblyVersion wants bare numbers, so it
// drops the zero padding; AssemblyInformationalVersion carries the exact tag
// text. The CI build rewrites all three from the version it is publishing,
// together with VERSION in patcher.py, so one number identifies the whole fix.
[assembly: AssemblyTitle("Life is Strange: Double Exposure - Ultrawide Fix")]
[assembly: AssemblyDescription("Installs the ultrawide and cutscene fix for "
                               + "Life is Strange: Double Exposure.")]
[assembly: AssemblyProduct("LiS:DE Ultrawide Fix")]
[assembly: AssemblyCopyright("Copyright (C) 2026 Kiri11. "
                             + "GPL-3.0-or-later; see LICENSE.")]
[assembly: AssemblyVersion("2026.8.31.1")]
[assembly: AssemblyFileVersion("2026.8.31.1")]
[assembly: AssemblyInformationalVersion("2026.08.31.1")]
[assembly: ComVisible(false)]

namespace LiSUltrawidePatcher
{
    public class MainForm : Form
    {
        [DllImport("user32.dll")]
        private static extern bool SetProcessDPIAware();

        private struct Preset
        {
            public string Name;
            public int W, H;
            public Preset(string n, int w, int h) { Name = n; W = w; H = h; }
        }

        private readonly List<Preset> presets = new List<Preset>
        {
            new Preset("5120x2160 (21:9 WUHD 4K)", 5120, 2160),
            new Preset("3440x1440 (21:9 UWQHD)", 3440, 1440),
            new Preset("2560x1080 (21:9 UWD)", 2560, 1080),
            new Preset("3840x1600 (24:10 UW)", 3840, 1600),
            new Preset("5120x1440 (32:9 Super Ultrawide)", 5120, 1440),
            new Preset("3840x1080 (32:9 Super Ultrawide)", 3840, 1080),
            new Preset("7680x2160 (32:9 Super Ultrawide)", 7680, 2160),
            new Preset("3840x1200 (32:10)", 3840, 1200),
            new Preset("2560x1600 (16:10)", 2560, 1600),
        };

        private TextBox txtExePath, txtWidth, txtHeight, txtLog;
        private ComboBox cmbPresets;
        private CheckBox chkExe, chkGameFiles, chkChromatic, chkSharpen;
        private Button btnBrowse, btnInstall, btnRestore;
        private Label lblCustom, lblX, lblExeStatus, lblFilesStatus;
        private ToolTip tips;
        private System.Windows.Forms.Timer checkTimer;

        public MainForm()
        {
            InitializeComponent();
            AutoDetect();
        }

        // ------------------------------------------------------------------ UI
        //
        // Everything here auto-sizes. An earlier version positioned each control
        // at a fixed pixel coordinate, which clipped every wrapped description
        // as soon as the system font metrics differed from the ones assumed.

        private const int ContentWidth = 560;

        private Label Header(string text)
        {
            Label l = new Label();
            l.Text = text;
            l.AutoSize = true;
            l.Margin = new Padding(0, 10, 0, 4);
            l.Font = new Font(Font, FontStyle.Bold);
            return l;
        }

        private CheckBox Option(TableLayoutPanel host, string title, string detail)
        {
            return Option(host, title, detail, true);
        }

        private CheckBox Option(TableLayoutPanel host, string title, string detail,
                                bool on)
        {
            CheckBox c = new CheckBox();
            c.Text = title;
            c.Checked = on;
            c.AutoSize = true;
            c.Margin = new Padding(0, 6, 0, 0);
            c.Font = new Font(Font, FontStyle.Bold);

            Label d = new Label();
            d.Text = detail;
            d.AutoSize = true;
            d.MaximumSize = new Size(ContentWidth - 24, 0);   // wraps, grows down
            d.Margin = new Padding(18, 0, 0, 2);
            d.ForeColor = SystemColors.GrayText;

            host.Controls.Add(c);
            host.Controls.Add(d);
            return c;
        }

        private void InitializeComponent()
        {
            Text = "Life is Strange: Double Exposure - Ultrawide Fix";
            AutoScaleMode = AutoScaleMode.Font;
            StartPosition = FormStartPosition.CenterScreen;
            Font = new Font("Segoe UI", 9F);
            ClientSize = new Size(600, 640);
            MinimumSize = new Size(560, 560);
            try { Icon = Icon.ExtractAssociatedIcon(Application.ExecutablePath); }
            catch { }

            TableLayoutPanel root = new TableLayoutPanel();
            root.Dock = DockStyle.Fill;
            root.ColumnCount = 1;
            root.Padding = new Padding(16, 8, 16, 12);
            root.AutoSize = false;
            Controls.Add(root);

            // --- game executable
            root.Controls.Add(Header("Game executable"));

            TableLayoutPanel exeRow = new TableLayoutPanel();
            exeRow.ColumnCount = 2;
            exeRow.Dock = DockStyle.Fill;      // the path box gets the whole row
            exeRow.AutoSize = true;
            exeRow.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            exeRow.Margin = new Padding(0, 0, 0, 4);
            exeRow.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            exeRow.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            txtExePath = new TextBox();
            txtExePath.Dock = DockStyle.Fill;
            btnBrowse = new Button();
            btnBrowse.Text = "Browse...";
            btnBrowse.AutoSize = true;
            btnBrowse.Margin = new Padding(6, 0, 0, 0);
            btnBrowse.Click += OnBrowse;
            exeRow.Controls.Add(txtExePath, 0, 0);
            exeRow.Controls.Add(btnBrowse, 1, 0);
            root.Controls.Add(exeRow);

            tips = new ToolTip();
            tips.AutoPopDelay = 20000;
            txtExePath.TextChanged += OnExePathChanged;

            checkTimer = new System.Windows.Forms.Timer();          // coalesces typing into one check
            checkTimer.Interval = 400;
            checkTimer.Tick += OnCheckTick;

            lblExeStatus = new Label();
            lblExeStatus.AutoSize = true;
            lblExeStatus.MaximumSize = new Size(ContentWidth, 0);
            lblExeStatus.ForeColor = SystemColors.GrayText;
            lblExeStatus.Margin = new Padding(2, 2, 0, 0);
            root.Controls.Add(lblExeStatus);

            // The second line is about the game's data rather than the exe: it
            // is the only way a user learns that a game update has left the
            // installed UI container behind, since nothing of ours runs at
            // launch to tell them.
            lblFilesStatus = new Label();
            lblFilesStatus.AutoSize = true;
            lblFilesStatus.MaximumSize = new Size(ContentWidth, 0);
            lblFilesStatus.ForeColor = SystemColors.GrayText;
            lblFilesStatus.Margin = new Padding(2, 0, 0, 0);
            root.Controls.Add(lblFilesStatus);

            // --- resolution
            root.Controls.Add(Header("Display resolution"));

            FlowLayoutPanel resRow = new FlowLayoutPanel();
            resRow.AutoSize = true;
            resRow.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            resRow.WrapContents = true;
            resRow.Margin = new Padding(0, 0, 0, 4);

            cmbPresets = new ComboBox();
            cmbPresets.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbPresets.Width = 250;
            cmbPresets.Margin = new Padding(0, 0, 10, 0);
            foreach (Preset p in presets) cmbPresets.Items.Add(p.Name);
            cmbPresets.Items.Add("Custom...");
            cmbPresets.SelectedIndexChanged += OnPresetChanged;
            resRow.Controls.Add(cmbPresets);

            lblCustom = new Label();
            lblCustom.Text = "Custom:";
            lblCustom.AutoSize = true;
            lblCustom.Margin = new Padding(0, 6, 4, 0);
            resRow.Controls.Add(lblCustom);

            txtWidth = new TextBox();
            txtWidth.Width = 52;
            resRow.Controls.Add(txtWidth);

            lblX = new Label();
            lblX.Text = "x";
            lblX.AutoSize = true;
            lblX.Margin = new Padding(2, 6, 2, 0);
            resRow.Controls.Add(lblX);

            txtHeight = new TextBox();
            txtHeight.Width = 52;
            resRow.Controls.Add(txtHeight);
            root.Controls.Add(resRow);

            // --- options
            root.Controls.Add(Header("What to install"));

            TableLayoutPanel opts = new TableLayoutPanel();
            opts.ColumnCount = 1;
            opts.AutoSize = true;
            opts.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            opts.Margin = new Padding(0, 0, 0, 2);

            chkExe = Option(opts, "Ultrawide camera",
                "Hor+ cutscenes, dialogue and exploration - no black bars, and no "
                + "zoom when a dialogue ends. Patches the executable.");
            chkGameFiles = Option(opts, "Full-width UI",
                "Loading screens cover the whole screen and the HUD sits on the "
                + "real screen edge. Patches the game data files.");
            chkChromatic = Option(opts, "Disable chromatic aberration",
                "Removes the colour fringing at the widened edges.");
            chkSharpen = Option(opts, "Reduce blurriness",
                "Recommended TSR settings for this resolution.", false);
            root.Controls.Add(opts);

            Label note = new Label();
            note.Text = "The last two write into Engine.ini. Restore removes them.";
            note.AutoSize = true;
            note.MaximumSize = new Size(ContentWidth, 0);
            note.ForeColor = SystemColors.GrayText;
            note.Margin = new Padding(0, 4, 0, 8);
            root.Controls.Add(note);

            // --- actions
            TableLayoutPanel buttons = new TableLayoutPanel();
            buttons.ColumnCount = 2;
            buttons.Dock = DockStyle.Fill;
            buttons.AutoSize = true;
            buttons.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            buttons.Margin = new Padding(0, 0, 0, 8);
            buttons.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            buttons.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));

            btnInstall = new Button();
            btnInstall.Text = "Install";
            btnInstall.Dock = DockStyle.Fill;
            btnInstall.Height = 34;
            btnInstall.Font = new Font(Font.FontFamily, 10F, FontStyle.Bold);
            btnInstall.Margin = new Padding(0, 0, 4, 0);
            btnInstall.Click += OnInstall;

            btnRestore = new Button();
            btnRestore.Text = "Restore original";
            btnRestore.Dock = DockStyle.Fill;
            btnRestore.Height = 34;
            btnRestore.Margin = new Padding(4, 0, 0, 0);
            btnRestore.Click += OnRestore;

            buttons.Controls.Add(btnInstall, 0, 0);
            buttons.Controls.Add(btnRestore, 1, 0);
            root.Controls.Add(buttons);

            // --- log, absorbs whatever space is left
            txtLog = new TextBox();
            txtLog.Multiline = true;
            txtLog.ScrollBars = ScrollBars.Vertical;
            txtLog.ReadOnly = true;
            txtLog.BackColor = Color.White;
            txtLog.Font = new Font("Consolas", 8.5F);
            txtLog.Dock = DockStyle.Fill;
            txtLog.Margin = new Padding(0);
            root.Controls.Add(txtLog);

            // every row hugs its content except the log, which takes the slack
            for (int i = 0; i < root.Controls.Count; i++)
                root.RowStyles.Add(new RowStyle(SizeType.AutoSize));
            root.RowCount = root.Controls.Count;
            root.RowStyles[root.RowCount - 1] = new RowStyle(SizeType.Percent, 100F);
        }

        // ------------------------------------------------------------- helpers

        private void Log(string s)
        {
            if (txtLog.InvokeRequired)
            {
                txtLog.BeginInvoke((MethodInvoker)delegate { Log(s); });
                return;
            }
            txtLog.AppendText(s + Environment.NewLine);
        }

        private void OnPresetChanged(object sender, EventArgs e)
        {
            bool custom = cmbPresets.SelectedIndex == presets.Count;
            txtWidth.Enabled = txtHeight.Enabled = custom;
            if (!custom && cmbPresets.SelectedIndex >= 0)
            {
                Preset p = presets[cmbPresets.SelectedIndex];
                txtWidth.Text = p.W.ToString();
                txtHeight.Text = p.H.ToString();
            }
        }

        private void OnBrowse(object sender, EventArgs e)
        {
            OpenFileDialog d = new OpenFileDialog();
            d.Filter = "Chronos-Win64-Shipping.exe|Chronos-Win64-Shipping.exe|All files|*.*";
            d.RestoreDirectory = true;
            // start where the current selection is, with that file selected
            string current = txtExePath.Text.Trim();
            if (current.Length > 0)
            {
                try
                {
                    string dir = Path.GetDirectoryName(Path.GetFullPath(current));
                    if (Directory.Exists(dir)) d.InitialDirectory = dir;
                    if (File.Exists(current)) d.FileName = Path.GetFileName(current);
                }
                catch { }
            }
            if (d.ShowDialog() == DialogResult.OK) txtExePath.Text = d.FileName;
        }

        // ---- locating the game ------------------------------------------
        // A lookup, not patch logic: this mirrors find_exe() in patcher.py so
        // the window can show the game path instantly, without starting Python
        // just to fill in a text box. patcher.py stays the source of truth for
        // everything that is written.

        private const string SteamAppId = "1874000";
        private const string GameDirName = "LifeIsStrangeDoubleExposure";
        private const string ExeName = "Chronos-Win64-Shipping.exe";
        private static readonly string ExeRelative =
            Path.Combine("Chronos", "Binaries", "Win64", ExeName);

        private static string ExeUnder(string gameRoot)
        {
            if (string.IsNullOrEmpty(gameRoot)) return null;
            try
            {
                string p = Path.GetFullPath(Path.Combine(gameRoot, ExeRelative));
                return File.Exists(p) ? p : null;
            }
            catch { return null; }
        }

        private static bool LooksLikeGame(string name)
        {
            StringBuilder flat = new StringBuilder();
            foreach (char c in name.ToLowerInvariant())
                if (char.IsLetterOrDigit(c)) flat.Append(c);
            return flat.ToString().Contains("doubleexposure");
        }

        private static string ReadTextFile(string path)
        {
            try { return File.ReadAllText(path); }
            catch { return ""; }
        }

        private static List<string> FixedDrives()
        {
            List<string> drives = new List<string>();
            try
            {
                foreach (DriveInfo d in DriveInfo.GetDrives())
                    if (d.DriveType == DriveType.Fixed && d.IsReady)
                        drives.Add(d.RootDirectory.FullName);
            }
            catch { }
            if (drives.Count == 0) drives.Add("C:\\");
            return drives;
        }

        private static void AddDir(List<string> list, string path)
        {
            if (string.IsNullOrEmpty(path)) return;
            try
            {
                if (!Directory.Exists(path)) return;
                // normalise, so C:/steam and C:\Steam are not scanned twice
                path = Path.GetFullPath(path);
            }
            catch { return; }
            string key = path.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            foreach (string existing in list)
                if (string.Equals(existing.TrimEnd(Path.DirectorySeparatorChar,
                                                Path.AltDirectorySeparatorChar), key,
                                  StringComparison.OrdinalIgnoreCase))
                    return;
            list.Add(path);
        }

        private static string RegistryValue(RegistryKey hive, string key, string name)
        {
            try
            {
                using (RegistryKey k = hive.OpenSubKey(key))
                    return (k == null) ? null : k.GetValue(name) as string;
            }
            catch { return null; }
        }

        // every Steam installation, plus each library folder it has registered
        private static List<string> SteamLibraries()
        {
            List<string> installs = new List<string>();
            AddDir(installs, RegistryValue(Registry.CurrentUser,
                                           "Software\\Valve\\Steam", "SteamPath"));
            AddDir(installs, RegistryValue(Registry.LocalMachine,
                                           "SOFTWARE\\WOW6432Node\\Valve\\Steam", "InstallPath"));
            AddDir(installs, RegistryValue(Registry.LocalMachine,
                                           "SOFTWARE\\Valve\\Steam", "InstallPath"));
            foreach (string drive in FixedDrives())
            {
                AddDir(installs, Path.Combine(drive, "Program Files (x86)\\Steam"));
                AddDir(installs, Path.Combine(drive, "Program Files\\Steam"));
                AddDir(installs, Path.Combine(drive, "Steam"));
            }

            List<string> libraries = new List<string>(installs);
            foreach (string install in installs)
            {
                string vdf = Path.Combine(install, "steamapps\\libraryfolders.vdf");
                if (!File.Exists(vdf)) continue;
                string text = ReadTextFile(vdf);
                // current format keys each entry "path"; the pre-2021 one used numbers
                foreach (string pattern in new[] { "\"path\"\\s*\"([^\"]+)\"",
                                                   "\"[0-9]+\"\\s*\"([^\"]{3,})\"" })
                    foreach (Match m in Regex.Matches(text, pattern))
                        AddDir(libraries, m.Groups[1].Value.Replace("\\\\", "\\"));
            }
            return libraries;
        }

        /// <summary>The game executable, wherever it is; source says how it was found.</summary>
        private static string FindGameExe(out string source)
        {
            source = null;

            // 1. beside this tool, or beside the folder it was started from
            string[] relatives = { ExeName, ExeRelative,
                                   Path.Combine("..", ExeRelative),
                                   Path.Combine("..", "..", ExeRelative) };
            string[] bases = { AppDomain.CurrentDomain.BaseDirectory,
                               Directory.GetCurrentDirectory() };
            foreach (string dir in bases)
                foreach (string rel in relatives)
                {
                    string full;
                    try { full = Path.GetFullPath(Path.Combine(dir, rel)); }
                    catch { continue; }
                    if (File.Exists(full)) { source = "the folder it was run from"; return full; }
                }

            // 2. every Steam library on the machine
            foreach (string library in SteamLibraries())
            {
                string apps = Path.Combine(library, "steamapps");
                string common = Path.Combine(apps, "common");
                if (!Directory.Exists(common)) continue;
                List<string> names = new List<string>();
                string manifest = Path.Combine(apps, "appmanifest_" + SteamAppId + ".acf");
                if (File.Exists(manifest))
                {
                    Match m = Regex.Match(ReadTextFile(manifest),
                                          "\"installdir\"\\s*\"([^\"]+)\"");
                    if (m.Success) names.Add(m.Groups[1].Value);
                }
                names.Add(GameDirName);
                try
                {
                    foreach (string d in Directory.GetDirectories(common))
                        if (LooksLikeGame(Path.GetFileName(d))) names.Add(Path.GetFileName(d));
                }
                catch { }
                foreach (string name in names)
                {
                    string hit = ExeUnder(Path.Combine(common, name));
                    if (hit != null) { source = "Steam library " + library; return hit; }
                }
            }

            // 3. whatever the Epic Games Launcher has installed
            try
            {
                string manifests = Path.Combine(
                    Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),
                    "Epic\\EpicGamesLauncher\\Data\\Manifests");
                foreach (string item in Directory.GetFiles(manifests, "*.item"))
                {
                    Match m = Regex.Match(ReadTextFile(item),
                                          "\"InstallLocation\"\\s*:\\s*\"([^\"]+)\"");
                    if (!m.Success) continue;
                    string hit = ExeUnder(m.Groups[1].Value.Replace("\\\\", "\\"));
                    if (hit != null) { source = "the Epic Games Launcher"; return hit; }
                }
            }
            catch { }

            // 4. the usual places a game folder ends up when no launcher claims it
            string[] commonRoots = { "Games", "Program Files", "Program Files (x86)",
                                     "GOG Games", "Epic Games",
                                     "SteamLibrary\\steamapps\\common",
                                     "Games\\steamapps\\common" };
            foreach (string drive in FixedDrives())
            {
                List<string> roots = new List<string> { drive };
                foreach (string rel in commonRoots) roots.Add(Path.Combine(drive, rel));
                foreach (string root in roots)
                {
                    string hit = ExeUnder(Path.Combine(root, GameDirName));
                    if (hit != null) { source = root; return hit; }
                    string[] entries;
                    try { entries = Directory.GetDirectories(root); }
                    catch { continue; }
                    foreach (string entry in entries)
                    {
                        if (!LooksLikeGame(Path.GetFileName(entry))) continue;
                        hit = ExeUnder(entry);
                        if (hit != null) { source = root; return hit; }
                    }
                }
            }
            return null;
        }

        private void AutoDetect()
        {
            // executable: beside this tool, then Steam, Epic and the usual roots
            string source;
            string exe = FindGameExe(out source);
            if (exe != null)
            {
                txtExePath.Text = exe;
                Log("Found game via " + source);
            }
            else
            {
                Log("Could not find the game automatically - use Browse.");
            }

            // resolution: select the preset matching this display, else Custom
            Rectangle b = Screen.PrimaryScreen.Bounds;
            txtWidth.Text = b.Width.ToString();
            txtHeight.Text = b.Height.ToString();
            int match = -1;
            for (int i = 0; i < presets.Count; i++)
                if (presets[i].W == b.Width && presets[i].H == b.Height) { match = i; break; }
            cmbPresets.SelectedIndex = (match >= 0) ? match : presets.Count;
            Log(string.Format("Detected display: {0}x{1}{2}", b.Width, b.Height,
                              match >= 0 ? "" : "  (using Custom)"));

            // show the start of the path rather than opening mid-selection
            txtExePath.SelectionLength = 0;
            txtExePath.SelectionStart = 0;
            ActiveControl = btnInstall;
        }

        // ---- executable status -------------------------------------------
        // What the file currently is (stock / already patched / unrecognised)
        // is decided by patcher.py --check-exe, which tests the very byte
        // signatures it patches through. Keeping the answer there means the
        // badge can never disagree with what Install would actually do.

        private const string GlyphOk = "\u2714";      // heavy check mark
        private const string GlyphWarn = "\u26A0";    // warning sign
        private static readonly Color OkColor = Color.FromArgb(0, 128, 0);
        private static readonly Color WarnColor = Color.FromArgb(190, 100, 0);

        private int checkToken;
        // uv would fetch an interpreter and blake3 the first time it runs the
        // script; a background badge must not trigger downloads, so uv is only
        // used for checks once a real Install/Restore has already primed it.
        private bool uvCheckAllowed;

        private void SetExeStatus(string glyph, Color color, string text, string tip)
        {
            lblExeStatus.ForeColor = color;
            lblExeStatus.Text = (glyph.Length > 0 ? glyph + "  " : "") + text;
            tips.SetToolTip(lblExeStatus, tip ?? text);
        }

        private void SetFilesStatus(string glyph, Color color, string text, string tip)
        {
            lblFilesStatus.ForeColor = color;
            lblFilesStatus.Text = text.Length == 0
                ? "" : (glyph.Length > 0 ? glyph + "  " : "") + text;
            tips.SetToolTip(lblFilesStatus, tip ?? text);
        }

        private void OnExePathChanged(object sender, EventArgs e)
        {
            tips.SetToolTip(txtExePath, txtExePath.Text.Trim());
            checkTimer.Stop();
            checkTimer.Start();          // coalesce typing into one check
        }

        private void OnCheckTick(object sender, EventArgs e)
        {
            checkTimer.Stop();
            StartExeCheck();
        }

        private void StartExeCheck()
        {
            if (!IsHandleCreated) return;
            string path = txtExePath.Text.Trim();
            int token = ++checkToken;

            if (path.Length == 0)
            {
                SetExeStatus("", SystemColors.GrayText, "No executable selected.", null);
                SetFilesStatus("", SystemColors.GrayText, "", null);
                return;
            }
            if (!File.Exists(path))
            {
                SetExeStatus(GlyphWarn, WarnColor, "There is no file at that path.", path);
                SetFilesStatus("", SystemColors.GrayText, "", null);
                return;
            }
            SetExeStatus("", SystemColors.GrayText,
                         "Checking " + Path.GetFileName(path) + "...", path);
            SetFilesStatus("", SystemColors.GrayText, "", null);

            ThreadPool.QueueUserWorkItem(delegate
            {
                string status, detail, files, filesDetail;
                RunCheck(path, out status, out detail, out files, out filesDetail);
                if (token != checkToken) return;             // superseded
                try
                {
                    BeginInvoke((MethodInvoker)delegate
                    {
                        if (token != checkToken) return;
                        ApplyStatus(status, detail);
                        ApplyFilesStatus(files, filesDetail);
                    });
                }
                catch { }                                    // form already gone
            });
        }

        /// <summary>The full-width UI container: is it there, and is it current?</summary>
        private void ApplyFilesStatus(string status, string detail)
        {
            switch (status)
            {
                case "current":
                    SetFilesStatus(GlyphOk, OkColor, "Full-width UI " + detail + ".", detail);
                    break;
                case "stale":
                    SetFilesStatus(GlyphWarn, WarnColor,
                                   "Full-width UI was built for a different build of the "
                                   + "game - Install again before playing.", detail);
                    break;
                case "unrecorded":
                case "incomplete":
                    SetFilesStatus(GlyphWarn, WarnColor,
                                   "Full-width UI needs installing again.", detail);
                    break;
                case "none":
                    SetFilesStatus("", SystemColors.GrayText,
                                   "Full-width UI is not installed.", detail);
                    break;
                default:
                    SetFilesStatus("", SystemColors.GrayText, "", detail);
                    break;
            }
        }

        private void ApplyStatus(string status, string detail)
        {
            switch (status)
            {
                case "original":
                    SetExeStatus(GlyphOk, OkColor,
                                 "Original executable - a build this patcher knows.", detail);
                    break;
                case "patched":
                    SetExeStatus(GlyphWarn, WarnColor,
                                 "Already patched - Install re-applies from the backup.",
                                 detail);
                    break;
                case "unknown":
                    SetExeStatus(GlyphWarn, WarnColor,
                                 "Unrecognised executable - a game update, or the wrong file.",
                                 detail);
                    break;
                case "missing":
                    SetExeStatus(GlyphWarn, WarnColor, "There is no file at that path.", detail);
                    break;
                case "norunner":
                    SetExeStatus("", SystemColors.GrayText,
                                 "Not checked - no Python found yet.",
                                 "Install or Restore still works: it fetches a private "
                                 + "Python if this machine has none.");
                    break;
                case "noscript":
                    SetExeStatus("", SystemColors.GrayText,
                                 "Not checked - patcher.py is not next to this program.", null);
                    break;
                default:
                    SetExeStatus("", SystemColors.GrayText, "Could not check this file.", detail);
                    break;
            }
        }

        /// <summary>patcher.py --check-exe, out of sight; never prompts.</summary>
        private void RunCheck(string path, out string status, out string detail,
                              out string files, out string filesDetail)
        {
            status = "error";
            detail = null;
            files = "error";
            filesDetail = null;
            string script = ScriptPath();
            if (script == null) { status = "noscript"; return; }

            List<string> argv = new List<string>();
            argv.Add("--check-exe");
            argv.Add("--exe");
            argv.Add("\"" + path + "\"");

            // Every runner in turn: one that cannot start Python at all must not
            // be the reason the badge says "could not check" while the next one
            // in the list would have answered.
            List<Runner> runners = Runners(script, argv, uvCheckAllowed);
            if (runners.Count == 0) { status = "norunner"; return; }

            foreach (Runner r in runners)
            {
                try
                {
                    using (Process p = Process.Start(Launch(r, script)))
                    {
                        // drained on its own thread: a runner that writes a
                        // long complaint to stderr would otherwise fill its
                        // pipe and hang while we read the other one
                        Process capture = p;
                        ThreadPool.QueueUserWorkItem(delegate
                        {
                            try { capture.StandardError.ReadToEnd(); }
                            catch { }
                        });
                        string text = p.StandardOutput.ReadToEnd();
                        p.WaitForExit();
                        bool answered = false;
                        foreach (string line in text.Split('\n'))
                        {
                            string t = line.Trim();
                            if (t.StartsWith("status: "))
                            {
                                status = t.Substring(8).Trim();
                                answered = true;
                            }
                            else if (t.StartsWith("detail: ")) detail = t.Substring(8).Trim();
                            else if (t.StartsWith("files: ")) files = t.Substring(7).Trim();
                            else if (t.StartsWith("filesdetail: "))
                                filesDetail = t.Substring(13).Trim();
                        }
                        if (answered) return;
                    }
                }
                catch (Exception ex)
                {
                    status = "error";
                    detail = ex.Message;
                }
            }
        }

        protected override void OnShown(EventArgs e)
        {
            base.OnShown(e);
            StartExeCheck();
        }

        // A machine with no Python at all still has to work.  Preference order is
        // uv (fastest, and it brings the compiled blake3), then whatever Python
        // is installed, then a private copy of python.org's embeddable build
        // unpacked into tools/python - ~11 MB to download, ~22 MB on disk, no
        // installer, no PATH changes, and it is deleted along with this fix.
        private const string PythonEmbedUrl =
            "https://www.python.org/ftp/python/3.12.10/python-3.12.10-embed-amd64.zip";

        /// <summary>Where a private interpreter may live, best place first.</summary>
        private static List<string> EmbeddedPythonDirs()
        {
            List<string> dirs = new List<string>();
            dirs.Add(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
                                  Path.Combine("tools", "python")));
            // the fix may have been unpacked somewhere unwritable - Program
            // Files, a shared drive - so keep a per-user location in reserve
            string local = Environment.GetFolderPath(
                Environment.SpecialFolder.LocalApplicationData);
            if (!string.IsNullOrEmpty(local))
                dirs.Add(Path.Combine(local, Path.Combine("LiSUltrawideFix", "python")));
            return dirs;
        }

        private static string EmbeddedPython()
        {
            foreach (string dir in EmbeddedPythonDirs())
            {
                string exe = Path.Combine(dir, "python.exe");
                if (File.Exists(exe)) return exe;
            }
            return null;
        }

        /// <summary>Can a file actually be created in there?</summary>
        private static bool Writable(string dir)
        {
            try
            {
                Directory.CreateDirectory(dir);
                string probe = Path.Combine(dir, ".write-probe");
                using (File.Create(probe)) { }
                File.Delete(probe);
                return true;
            }
            catch { return false; }
        }

        /// <summary>Fetch python.org's embeddable build into tools/python.</summary>
        private string FetchEmbeddedPython()
        {
            string dir = null;
            foreach (string candidate in EmbeddedPythonDirs())
            {
                if (Writable(candidate)) { dir = candidate; break; }
                Log("Cannot write to " + candidate + " - trying elsewhere.");
            }
            if (dir == null)
            {
                Log("No writable place to put an interpreter.");
                return null;
            }
            string zip = Path.Combine(Path.GetTempPath(), "lisde-python-embed.zip");
            try
            {
                Log("No Python on this machine - fetching a private copy (~11 MB):");
                Log("  " + PythonEmbedUrl);
                Log("  into " + dir);
                Application.DoEvents();
                // the 4.0 default protocol list predates TLS 1.2, which python.org requires
                ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;
                using (WebClient wc = new WebClient())
                {
                    wc.Headers.Add("User-Agent", "LiSUltrawideFix");
                    wc.DownloadFile(PythonEmbedUrl, zip);
                }
                if (Directory.Exists(dir)) Directory.Delete(dir, true);
                Directory.CreateDirectory(dir);
                ZipFile.ExtractToDirectory(zip, dir);
                string exe = Path.Combine(dir, "python.exe");
                if (!File.Exists(exe))
                {
                    Log("  the archive contained no python.exe");
                    return null;
                }
                Log("  Python ready: " + exe);
                return exe;
            }
            catch (Exception ex)
            {
                Log("  could not fetch Python: " + ex.Message);
                return null;
            }
            finally
            {
                try { if (File.Exists(zip)) File.Delete(zip); }
                catch { }
            }
        }

        /// <summary>uv from PATH, or from the locations its installer uses.</summary>
        private static string FindUv()
        {
            string onPath = Which("uv");
            if (onPath != null) return onPath;
            // A freshly installed uv is not on THIS process's PATH, which was
            // captured at launch - so look where the installer puts it.
            string home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
            string[] dirs = {
                Path.Combine(home, ".local", "bin"),
                Path.Combine(home, ".cargo", "bin"),
            };
            foreach (string d in dirs)
            {
                try
                {
                    string f = Path.Combine(d, "uv.exe");
                    if (File.Exists(f)) return f;
                }
                catch { }
            }
            return null;
        }

        /// <summary>One way of running patcher.py, in preference order.</summary>
        private struct Runner
        {
            public string Exe, Args, Label;
            public Runner(string exe, string args, string label)
            {
                Exe = exe; Args = args; Label = label;
            }
        }

        /// <summary>Every way this machine can run the script, best first.</summary>
        //
        // uv is first because it brings its own interpreter and the compiled
        // blake3 - but it needs the network to do so, so a machine that is
        // offline, or behind a proxy, gets nothing from it. That is why this
        // returns a LIST: Run() falls through to the next entry when a runner
        // fails before the patcher itself ever printed anything.
        private List<Runner> Runners(string script, List<string> argv, bool allowUv)
        {
            StringBuilder tail = new StringBuilder();
            tail.Append('"').Append(script).Append('"');
            foreach (string a in argv) tail.Append(' ').Append(a);

            List<Runner> list = new List<Runner>();
            string uv = allowUv ? FindUv() : null;
            if (uv != null)
                list.Add(new Runner(uv, "run --quiet --script " + tail, "uv"));
            string py = Which("py");
            if (py != null) list.Add(new Runner(py, "-3 " + tail, "the Python launcher"));
            string python = Which("python");
            if (python != null) list.Add(new Runner(python, tail.ToString(), "Python"));
            string embedded = EmbeddedPython();
            if (embedded != null)
                list.Add(new Runner(embedded, tail.ToString(), "the private Python"));
            return list;
        }

        /// <summary>Start settings shared by every way of running the script.</summary>
        //
        // The encodings matter: without them the child writes in the machine's
        // ANSI code page while this process reads the OEM one, so a game path
        // with a non-ASCII character in it arrives as mojibake - and Python
        // raises UnicodeEncodeError rather than printing it at all. UTF-8 on
        // both sides is the only pair that agrees on every Windows.
        // Both streams are always redirected: .NET refuses to start a process
        // that carries an encoding for a stream it is not capturing, so setting
        // one without the other throws instead of running anything.
        private static ProcessStartInfo Launch(Runner r, string script)
        {
            ProcessStartInfo psi = new ProcessStartInfo(r.Exe, r.Args);
            psi.UseShellExecute = false;
            psi.CreateNoWindow = true;
            psi.RedirectStandardOutput = true;
            psi.RedirectStandardError = true;
            psi.StandardOutputEncoding = new UTF8Encoding(false);
            psi.StandardErrorEncoding = new UTF8Encoding(false);
            psi.EnvironmentVariables["PYTHONUTF8"] = "1";
            psi.EnvironmentVariables["PYTHONIOENCODING"] = "utf-8";
            psi.WorkingDirectory = Path.GetDirectoryName(script);
            return psi;
        }

        private static string Which(string name)
        {
            string path = Environment.GetEnvironmentVariable("PATH");
            if (path == null) return null;
            foreach (string dir in path.Split(';'))
            {
                if (dir.Length == 0) continue;
                foreach (string ext in new[] { ".exe", ".cmd", ".bat" })
                {
                    try
                    {
                        string f = Path.Combine(dir.Trim('"'), name + ext);
                        if (File.Exists(f) && !IsStoreAlias(f)) return f;
                    }
                    catch { }
                }
            }
            return null;
        }

        /// <summary>Is this the Microsoft Store's python.exe placeholder?</summary>
        //
        // Windows ships zero-byte "app execution aliases" in WindowsApps, and
        // python.exe is one of them on a machine that has never installed
        // Python. It is a real file, so File.Exists says yes; running it opens
        // the Store and exits without doing anything. Taking it for an
        // interpreter is exactly how a clean PC ends up unable to install.
        private static bool IsStoreAlias(string file)
        {
            if (file.IndexOf("\\WindowsApps\\", StringComparison.OrdinalIgnoreCase) >= 0)
                return true;
            try
            {
                return new FileInfo(file).Length == 0;
            }
            catch { return false; }
        }

        private string ScriptPath()
        {
            string baseDir = AppDomain.CurrentDomain.BaseDirectory;
            string p = Path.Combine(baseDir, "patcher.py");
            return File.Exists(p) ? p : null;
        }

        private void Run(List<string> argv)
        {
            string script = ScriptPath();
            if (script == null)
            {
                MessageBox.Show("patcher.py must sit next to this program.",
                                "Missing patcher.py", MessageBoxButtons.OK,
                                MessageBoxIcon.Error);
                return;
            }
            List<Runner> runners = Runners(script, argv, true);
            if (runners.Count == 0)
            {
                txtLog.Clear();
                if (FetchEmbeddedPython() == null)
                {
                    MessageBox.Show(
                        "Nothing to run the patcher with, and the interpreter "
                        + "download failed.\r\n\r\n"
                        + "Check the connection and try again, or install Python "
                        + "3.8+ (python.org) and make sure it is on PATH.",
                        "No Python", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return;
                }
                runners = Runners(script, argv, true);
                if (runners.Count == 0) return;
            }

            btnInstall.Enabled = btnRestore.Enabled = false;
            txtLog.Clear();
            RunWith(runners, 0, script, argv);
        }

        /// <summary>Anything the patcher prints starts with this banner.</summary>
        private const string BannerMark = "Ultrawide Fix v";

        // The one thing this program must never do is decide on its own to run
        // an install twice. Falling through to the next runner is safe only
        // because the banner above is the patcher's first line: no banner means
        // the interpreter never got as far as the script, so nothing was
        // written and re-running from scratch cannot stack anything.
        private void RunWith(List<Runner> runners, int index, string script,
                             List<string> argv)
        {
            Runner r = runners[index];
            Log("> " + r.Exe + " " + r.Args);
            Log("");

            ProcessStartInfo psi = Launch(r, script);

            bool started = false;         // did the patcher itself ever speak?
            bool denied = false;          // ...and was it a permissions refusal?
            Process proc = new Process();
            proc.StartInfo = psi;
            proc.EnableRaisingEvents = true;
            DataReceivedEventHandler onLine = delegate(object s, DataReceivedEventArgs e)
            {
                if (e.Data == null) return;
                if (e.Data.IndexOf(BannerMark, StringComparison.Ordinal) >= 0)
                    started = true;
                // both patcher.py and the UI-layout step end that advice this
                // way ("run this installer as administrator" / "run the
                // installer as administrator")
                if (e.Data.IndexOf("as administrator",
                                   StringComparison.OrdinalIgnoreCase) >= 0)
                    denied = true;
                Log(e.Data);
            };
            proc.OutputDataReceived += onLine;
            proc.ErrorDataReceived += onLine;
            proc.Exited += delegate
            {
                int code = proc.ExitCode;
                BeginInvoke((MethodInvoker)delegate
                {
                    if (code != 0 && !started && index + 1 < runners.Count)
                    {
                        Log("");
                        Log(r.Label + " could not start the patcher (exit code "
                            + code + ") - trying " + runners[index + 1].Label + ".");
                        Log("");
                        RunWith(runners, index + 1, script, argv);
                        return;
                    }
                    Log("");
                    Log(code == 0 ? "Finished." : "Failed (exit code " + code + ").");
                    btnInstall.Enabled = btnRestore.Enabled = true;
                    uvCheckAllowed = true;     // whatever runs the patcher is primed now
                    StartExeCheck();           // the executable just changed
                    if (code != 0 && denied) OfferElevation(r, script);
                });
            };
            try
            {
                proc.Start();
                proc.BeginOutputReadLine();
                proc.BeginErrorReadLine();
            }
            catch (Exception ex)
            {
                Log("Could not start " + r.Exe + ": " + ex.Message);
                if (index + 1 < runners.Count)
                {
                    Log("Trying " + runners[index + 1].Label + ".");
                    Log("");
                    RunWith(runners, index + 1, script, argv);
                    return;
                }
                btnInstall.Enabled = btnRestore.Enabled = true;
            }
        }

        // A game under Program Files - Steam's default - cannot be written by an
        // ordinary process, and "right-click, Run as administrator" is not
        // something this program can assume anyone knows. So it offers, and
        // repeats the exact same command with the elevation prompt attached.
        private void OfferElevation(Runner r, string script)
        {
            if (MessageBox.Show(
                    "Windows refused permission to write the game files.\r\n\r\n"
                    + "This happens when the game is installed under Program "
                    + "Files. Run the same install again as administrator?",
                    "Administrator rights needed", MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question) != DialogResult.Yes)
                return;
            RunElevated(r, script);
        }

        /// <summary>The same command, elevated, with its output in a file.</summary>
        //
        // An elevated child cannot have its pipes redirected (that needs
        // UseShellExecute = false, which in turn cannot request elevation), so
        // it is run through cmd with its output sent to a temporary file, which
        // is poured into the log when it finishes.
        private void RunElevated(Runner r, string script)
        {
            string log = Path.Combine(Path.GetTempPath(), "lisde-elevated.log");
            try { if (File.Exists(log)) File.Delete(log); }
            catch { }

            // Elevation can land in a different account - a standard user who
            // types an administrator's password gets that administrator's
            // profile - and then %LOCALAPPDATA% is the wrong one: Engine.ini
            // would be written where the game will never read it. It is the
            // invoking user's, so pass theirs through.
            string local = Environment.GetFolderPath(
                Environment.SpecialFolder.LocalApplicationData);
            string keepLocal = string.IsNullOrEmpty(local)
                ? "" : "set \"LOCALAPPDATA=" + local + "\"&& ";
            string command = "set PYTHONUTF8=1&& set PYTHONIOENCODING=utf-8&& "
                             + keepLocal
                             + "\"" + r.Exe + "\" " + r.Args
                             + " > \"" + log + "\" 2>&1";
            ProcessStartInfo psi = new ProcessStartInfo("cmd.exe", "/c \"" + command + "\"");
            psi.UseShellExecute = true;          // required for the elevation verb
            psi.Verb = "runas";
            psi.WindowStyle = ProcessWindowStyle.Hidden;
            psi.WorkingDirectory = Path.GetDirectoryName(script);

            btnInstall.Enabled = btnRestore.Enabled = false;
            Log("");
            Log("Running as administrator - the output appears when it finishes.");
            Process proc;
            try
            {
                proc = Process.Start(psi);
            }
            catch (Exception ex)
            {
                // 1223 is the user dismissing the UAC prompt: not an error
                Log(ex is System.ComponentModel.Win32Exception
                    && ((System.ComponentModel.Win32Exception)ex).NativeErrorCode == 1223
                    ? "Cancelled - nothing was changed."
                    : "Could not start it as administrator: " + ex.Message);
                btnInstall.Enabled = btnRestore.Enabled = true;
                return;
            }
            proc.EnableRaisingEvents = true;
            proc.Exited += delegate
            {
                int code = proc.ExitCode;
                string text = "";
                try
                {
                    if (File.Exists(log))
                        text = File.ReadAllText(log, new UTF8Encoding(false));
                }
                catch (Exception ex) { text = "(could not read the output: " + ex.Message + ")"; }
                BeginInvoke((MethodInvoker)delegate
                {
                    foreach (string line in text.Replace("\r\n", "\n").Split('\n'))
                        if (line.Length > 0) Log(line);
                    Log("");
                    Log(code == 0 ? "Finished." : "Failed (exit code " + code + ").");
                    btnInstall.Enabled = btnRestore.Enabled = true;
                    StartExeCheck();
                    try { if (File.Exists(log)) File.Delete(log); }
                    catch { }
                });
            };
        }

        private bool CommonArgs(List<string> argv)
        {
            if (txtExePath.Text.Trim().Length == 0)
            {
                MessageBox.Show("Select the game executable first.", "No executable",
                                MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            int w, h;
            if (!int.TryParse(txtWidth.Text.Trim(), out w) ||
                !int.TryParse(txtHeight.Text.Trim(), out h) || w <= 0 || h <= 0)
            {
                MessageBox.Show("Enter a valid resolution.", "Invalid resolution",
                                MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            argv.Add("--exe");
            argv.Add("\"" + txtExePath.Text.Trim() + "\"");
            argv.Add("--width");
            argv.Add(w.ToString());
            argv.Add("--height");
            argv.Add(h.ToString());
            argv.Add("--yes");
            return true;
        }

        private void OnInstall(object sender, EventArgs e)
        {
            List<string> argv = new List<string>();
            if (!CommonArgs(argv)) return;
            if (!chkExe.Checked && !chkGameFiles.Checked &&
                !chkChromatic.Checked && !chkSharpen.Checked)
            {
                MessageBox.Show("Nothing is selected.", "Nothing to do",
                                MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }
            if (!chkExe.Checked) argv.Add("--no-exe");
            if (!chkGameFiles.Checked) argv.Add("--no-game-files");
            if (!chkChromatic.Checked) argv.Add("--no-chromatic-fix");
            if (chkSharpen.Checked) argv.Add("--sharpen");
            Run(argv);
        }

        private void OnRestore(object sender, EventArgs e)
        {
            List<string> argv = new List<string>();
            if (!CommonArgs(argv)) return;
            argv.Add("--restore");
            Run(argv);
        }

        [STAThread]
        public static void Main()
        {
            // Must happen BEFORE any window exists - doing it later makes Windows
            // re-map an already-created form and shrink it by the DPI factor.
            try { SetProcessDPIAware(); }
            catch { }
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
        }
    }
}
